SCRAPER_RETRIES = 3
SCRAPER_RETRIES_DELAY = 30

DELAY_BETWEEN_SEARCHES = 10
DELAY_BETWEEN_PAGES = 10
DELAY_BETWEEN_LINKS = 5
TOTAL_PAGES_TO_SCRAPE = 2

POST_CODE = 'GU10 1QD'
DISCORD_MESSAGE_DELAY = 5
